// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package editorial

type Marker struct {
	ID        string
	SessionID string
	SortOrder int64
	Name      string
	Type      string
	StartMs   int64
	EndMs     int64
	Publish   bool
	Source    string
	CreatedAt int64
	UpdatedAt int64
}

type Session struct {
	ID        string
	Vxid      string
	Title     string
	Status    string
	CreatedBy string
	CreatedAt int64
	UpdatedAt int64
}
