// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package editorial

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, vxid, title, status, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	Vxid      string
	Title     string
	Status    string
	CreatedBy string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Vxid,
		arg.Title,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMarkersForSession = `-- name: DeleteMarkersForSession :exec
DELETE FROM markers
WHERE session_id = ?
`

func (q *Queries) DeleteMarkersForSession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteMarkersForSession, sessionID)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSession = `-- name: GetSession :one
SELECT id, vxid, title, status, created_by, created_at, updated_at FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Vxid,
		&i.Title,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMarker = `-- name: InsertMarker :exec
INSERT INTO markers (id, session_id, sort_order, name, type, start_ms, end_ms, publish, source, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMarkerParams struct {
	ID        string
	SessionID string
	SortOrder int64
	Name      string
	Type      string
	StartMs   int64
	EndMs     int64
	Publish   bool
	Source    string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertMarker(ctx context.Context, arg InsertMarkerParams) error {
	_, err := q.db.ExecContext(ctx, insertMarker,
		arg.ID,
		arg.SessionID,
		arg.SortOrder,
		arg.Name,
		arg.Type,
		arg.StartMs,
		arg.EndMs,
		arg.Publish,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listMarkersForSession = `-- name: ListMarkersForSession :many
SELECT id, session_id, sort_order, name, type, start_ms, end_ms, publish, source, created_at, updated_at FROM markers
WHERE session_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) ListMarkersForSession(ctx context.Context, sessionID string) ([]Marker, error) {
	rows, err := q.db.QueryContext(ctx, listMarkersForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Marker
	for rows.Next() {
		var i Marker
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SortOrder,
			&i.Name,
			&i.Type,
			&i.StartMs,
			&i.EndMs,
			&i.Publish,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, vxid, title, status, created_by, created_at, updated_at FROM sessions
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Vxid,
			&i.Title,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMarkerPublish = `-- name: SetMarkerPublish :execrows
UPDATE markers SET publish = ?, updated_at = ?
WHERE id = ? AND session_id = ?
`

type SetMarkerPublishParams struct {
	Publish   bool
	UpdatedAt int64
	ID        string
	SessionID string
}

func (q *Queries) SetMarkerPublish(ctx context.Context, arg SetMarkerPublishParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMarkerPublish,
		arg.Publish,
		arg.UpdatedAt,
		arg.ID,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET updated_at = ?
WHERE id = ?
`

type TouchSessionParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.UpdatedAt, arg.ID)
	return err
}

const updateSessionTitle = `-- name: UpdateSessionTitle :execrows
UPDATE sessions SET title = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionTitleParams struct {
	Title     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionTitle, arg.Title, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
