// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/api.proto

package apiv1connect

import (
	v1 "bcc-media-tools/api/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// APIServiceName is the fully-qualified name of the APIService service.
	APIServiceName = "api.v1.APIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// APIServiceGetPermissionsProcedure is the fully-qualified name of the APIService's GetPermissions
	// RPC.
	APIServiceGetPermissionsProcedure = "/api.v1.APIService/GetPermissions"
	// APIServiceUpdatePermissionsProcedure is the fully-qualified name of the APIService's
	// UpdatePermissions RPC.
	APIServiceUpdatePermissionsProcedure = "/api.v1.APIService/UpdatePermissions"
	// APIServiceDeletePermissionsProcedure is the fully-qualified name of the APIService's
	// DeletePermissions RPC.
	APIServiceDeletePermissionsProcedure = "/api.v1.APIService/DeletePermissions"
	// APIServiceListPermissionsProcedure is the fully-qualified name of the APIService's
	// ListPermissions RPC.
	APIServiceListPermissionsProcedure = "/api.v1.APIService/ListPermissions"
	// APIServiceGetTranscriptionProcedure is the fully-qualified name of the APIService's
	// GetTranscription RPC.
	APIServiceGetTranscriptionProcedure = "/api.v1.APIService/GetTranscription"
	// APIServiceGetPreviewProcedure is the fully-qualified name of the APIService's GetPreview RPC.
	APIServiceGetPreviewProcedure = "/api.v1.APIService/GetPreview"
	// APIServiceSubmitTranscriptionProcedure is the fully-qualified name of the APIService's
	// SubmitTranscription RPC.
	APIServiceSubmitTranscriptionProcedure = "/api.v1.APIService/SubmitTranscription"
	// APIServiceGetYearsProcedure is the fully-qualified name of the APIService's GetYears RPC.
	APIServiceGetYearsProcedure = "/api.v1.APIService/GetYears"
	// APIServiceGetAlbumsProcedure is the fully-qualified name of the APIService's GetAlbums RPC.
	APIServiceGetAlbumsProcedure = "/api.v1.APIService/GetAlbums"
	// APIServiceGetAlbumTracksProcedure is the fully-qualified name of the APIService's GetAlbumTracks
	// RPC.
	APIServiceGetAlbumTracksProcedure = "/api.v1.APIService/GetAlbumTracks"
	// APIServiceGetPodcastTracksProcedure is the fully-qualified name of the APIService's
	// GetPodcastTracks RPC.
	APIServiceGetPodcastTracksProcedure = "/api.v1.APIService/GetPodcastTracks"
	// APIServiceGetLanguagesProcedure is the fully-qualified name of the APIService's GetLanguages RPC.
	APIServiceGetLanguagesProcedure = "/api.v1.APIService/GetLanguages"
	// APIServiceGetBMMTranscriptionProcedure is the fully-qualified name of the APIService's
	// GetBMMTranscription RPC.
	APIServiceGetBMMTranscriptionProcedure = "/api.v1.APIService/GetBMMTranscription"
	// APIServiceSubmitShortProcedure is the fully-qualified name of the APIService's SubmitShort RPC.
	APIServiceSubmitShortProcedure = "/api.v1.APIService/SubmitShort"
	// APIServiceGetExportConfigProcedure is the fully-qualified name of the APIService's
	// GetExportConfig RPC.
	APIServiceGetExportConfigProcedure = "/api.v1.APIService/GetExportConfig"
	// APIServiceStartExportProcedure is the fully-qualified name of the APIService's StartExport RPC.
	APIServiceStartExportProcedure = "/api.v1.APIService/StartExport"
	// APIServiceExportTimedMetadataProcedure is the fully-qualified name of the APIService's
	// ExportTimedMetadata RPC.
	APIServiceExportTimedMetadataProcedure = "/api.v1.APIService/ExportTimedMetadata"
	// APIServiceResolveAssetsProcedure is the fully-qualified name of the APIService's ResolveAssets
	// RPC.
	APIServiceResolveAssetsProcedure = "/api.v1.APIService/ResolveAssets"
	// APIServiceGetVBExportConfigProcedure is the fully-qualified name of the APIService's
	// GetVBExportConfig RPC.
	APIServiceGetVBExportConfigProcedure = "/api.v1.APIService/GetVBExportConfig"
	// APIServiceStartVBExportProcedure is the fully-qualified name of the APIService's StartVBExport
	// RPC.
	APIServiceStartVBExportProcedure = "/api.v1.APIService/StartVBExport"
	// APIServiceGetExportDestinationsProcedure is the fully-qualified name of the APIService's
	// GetExportDestinations RPC.
	APIServiceGetExportDestinationsProcedure = "/api.v1.APIService/GetExportDestinations"
	// APIServiceTriggerCantemoActionProcedure is the fully-qualified name of the APIService's
	// TriggerCantemoAction RPC.
	APIServiceTriggerCantemoActionProcedure = "/api.v1.APIService/TriggerCantemoAction"
	// APIServiceVaultSearchProcedure is the fully-qualified name of the APIService's VaultSearch RPC.
	APIServiceVaultSearchProcedure = "/api.v1.APIService/VaultSearch"
	// APIServiceGetVaultItemProcedure is the fully-qualified name of the APIService's GetVaultItem RPC.
	APIServiceGetVaultItemProcedure = "/api.v1.APIService/GetVaultItem"
)

// APIServiceClient is a client for the api.v1.APIService service.
type APIServiceClient interface {
	// Permissions
	GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error)
	UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error)
	DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error)
	ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error)
	// Transcriptions
	GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error)
	GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error)
	SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error)
	// BMM
	GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error)
	GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error)
	GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error)
	GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error)
	// Shorts
	SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error)
	// Export
	GetExportConfig(context.Context, *connect.Request[v1.GetExportConfigRequest]) (*connect.Response[v1.GetExportConfigResponse], error)
	StartExport(context.Context, *connect.Request[v1.StartExportRequest]) (*connect.Response[v1.StartExportResponse], error)
	ExportTimedMetadata(context.Context, *connect.Request[v1.ExportTimedMetadataRequest]) (*connect.Response[v1.Void], error)
	// Resolve VX-ids to titles for the bulk-export asset list
	ResolveAssets(context.Context, *connect.Request[v1.ResolveAssetsRequest]) (*connect.Response[v1.ResolveAssetsResponse], error)
	// VB Export
	GetVBExportConfig(context.Context, *connect.Request[v1.GetVBExportConfigRequest]) (*connect.Response[v1.GetVBExportConfigResponse], error)
	StartVBExport(context.Context, *connect.Request[v1.StartVBExportRequest]) (*connect.Response[v1.StartVBExportResponse], error)
	// Full destination lists for the admin permission editor
	GetExportDestinations(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.ExportDestinationsResponse], error)
	// Cantemo action panel
	TriggerCantemoAction(context.Context, *connect.Request[v1.TriggerCantemoActionRequest]) (*connect.Response[v1.Void], error)
	// VAULT (Vidispine search)
	VaultSearch(context.Context, *connect.Request[v1.VaultSearchRequest]) (*connect.Response[v1.VaultSearchResponse], error)
	GetVaultItem(context.Context, *connect.Request[v1.GetVaultItemRequest]) (*connect.Response[v1.GetVaultItemResponse], error)
}

// NewAPIServiceClient constructs a client for the api.v1.APIService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAPIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) APIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	aPIServiceMethods := v1.File_api_v1_api_proto.Services().ByName("APIService").Methods()
	return &aPIServiceClient{
		getPermissions: connect.NewClient[v1.Void, v1.Permissions](
			httpClient,
			baseURL+APIServiceGetPermissionsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetPermissions")),
			connect.WithClientOptions(opts...),
		),
		updatePermissions: connect.NewClient[v1.SetPermissionsRequest, v1.Void](
			httpClient,
			baseURL+APIServiceUpdatePermissionsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("UpdatePermissions")),
			connect.WithClientOptions(opts...),
		),
		deletePermissions: connect.NewClient[v1.DeletePermissionsRequest, v1.Void](
			httpClient,
			baseURL+APIServiceDeletePermissionsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("DeletePermissions")),
			connect.WithClientOptions(opts...),
		),
		listPermissions: connect.NewClient[v1.Void, v1.PermissionsList](
			httpClient,
			baseURL+APIServiceListPermissionsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("ListPermissions")),
			connect.WithClientOptions(opts...),
		),
		getTranscription: connect.NewClient[v1.GetTranscriptionReqest, v1.Transcription](
			httpClient,
			baseURL+APIServiceGetTranscriptionProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetTranscription")),
			connect.WithClientOptions(opts...),
		),
		getPreview: connect.NewClient[v1.GetPreviewRequest, v1.Preview](
			httpClient,
			baseURL+APIServiceGetPreviewProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetPreview")),
			connect.WithClientOptions(opts...),
		),
		submitTranscription: connect.NewClient[v1.SubmitTranscriptionRequest, v1.Void](
			httpClient,
			baseURL+APIServiceSubmitTranscriptionProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("SubmitTranscription")),
			connect.WithClientOptions(opts...),
		),
		getYears: connect.NewClient[v1.GetYearsRequest, v1.GetYearsResponse](
			httpClient,
			baseURL+APIServiceGetYearsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetYears")),
			connect.WithClientOptions(opts...),
		),
		getAlbums: connect.NewClient[v1.GetAlbumsRequest, v1.AlbumsList](
			httpClient,
			baseURL+APIServiceGetAlbumsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetAlbums")),
			connect.WithClientOptions(opts...),
		),
		getAlbumTracks: connect.NewClient[v1.GetAlbumTracksRequest, v1.TracksList](
			httpClient,
			baseURL+APIServiceGetAlbumTracksProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetAlbumTracks")),
			connect.WithClientOptions(opts...),
		),
		getPodcastTracks: connect.NewClient[v1.GetPodcastTracksRequest, v1.TracksList](
			httpClient,
			baseURL+APIServiceGetPodcastTracksProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetPodcastTracks")),
			connect.WithClientOptions(opts...),
		),
		getLanguages: connect.NewClient[v1.GetAvailableLanguagesRequest, v1.LanguageList](
			httpClient,
			baseURL+APIServiceGetLanguagesProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetLanguages")),
			connect.WithClientOptions(opts...),
		),
		getBMMTranscription: connect.NewClient[v1.GetBMMTranscriptionRequest, v1.Transcription](
			httpClient,
			baseURL+APIServiceGetBMMTranscriptionProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetBMMTranscription")),
			connect.WithClientOptions(opts...),
		),
		submitShort: connect.NewClient[v1.SubmitShortRequest, v1.Void](
			httpClient,
			baseURL+APIServiceSubmitShortProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("SubmitShort")),
			connect.WithClientOptions(opts...),
		),
		getExportConfig: connect.NewClient[v1.GetExportConfigRequest, v1.GetExportConfigResponse](
			httpClient,
			baseURL+APIServiceGetExportConfigProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetExportConfig")),
			connect.WithClientOptions(opts...),
		),
		startExport: connect.NewClient[v1.StartExportRequest, v1.StartExportResponse](
			httpClient,
			baseURL+APIServiceStartExportProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("StartExport")),
			connect.WithClientOptions(opts...),
		),
		exportTimedMetadata: connect.NewClient[v1.ExportTimedMetadataRequest, v1.Void](
			httpClient,
			baseURL+APIServiceExportTimedMetadataProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("ExportTimedMetadata")),
			connect.WithClientOptions(opts...),
		),
		resolveAssets: connect.NewClient[v1.ResolveAssetsRequest, v1.ResolveAssetsResponse](
			httpClient,
			baseURL+APIServiceResolveAssetsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("ResolveAssets")),
			connect.WithClientOptions(opts...),
		),
		getVBExportConfig: connect.NewClient[v1.GetVBExportConfigRequest, v1.GetVBExportConfigResponse](
			httpClient,
			baseURL+APIServiceGetVBExportConfigProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetVBExportConfig")),
			connect.WithClientOptions(opts...),
		),
		startVBExport: connect.NewClient[v1.StartVBExportRequest, v1.StartVBExportResponse](
			httpClient,
			baseURL+APIServiceStartVBExportProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("StartVBExport")),
			connect.WithClientOptions(opts...),
		),
		getExportDestinations: connect.NewClient[v1.Void, v1.ExportDestinationsResponse](
			httpClient,
			baseURL+APIServiceGetExportDestinationsProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetExportDestinations")),
			connect.WithClientOptions(opts...),
		),
		triggerCantemoAction: connect.NewClient[v1.TriggerCantemoActionRequest, v1.Void](
			httpClient,
			baseURL+APIServiceTriggerCantemoActionProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("TriggerCantemoAction")),
			connect.WithClientOptions(opts...),
		),
		vaultSearch: connect.NewClient[v1.VaultSearchRequest, v1.VaultSearchResponse](
			httpClient,
			baseURL+APIServiceVaultSearchProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("VaultSearch")),
			connect.WithClientOptions(opts...),
		),
		getVaultItem: connect.NewClient[v1.GetVaultItemRequest, v1.GetVaultItemResponse](
			httpClient,
			baseURL+APIServiceGetVaultItemProcedure,
			connect.WithSchema(aPIServiceMethods.ByName("GetVaultItem")),
			connect.WithClientOptions(opts...),
		),
	}
}

// aPIServiceClient implements APIServiceClient.
type aPIServiceClient struct {
	getPermissions        *connect.Client[v1.Void, v1.Permissions]
	updatePermissions     *connect.Client[v1.SetPermissionsRequest, v1.Void]
	deletePermissions     *connect.Client[v1.DeletePermissionsRequest, v1.Void]
	listPermissions       *connect.Client[v1.Void, v1.PermissionsList]
	getTranscription      *connect.Client[v1.GetTranscriptionReqest, v1.Transcription]
	getPreview            *connect.Client[v1.GetPreviewRequest, v1.Preview]
	submitTranscription   *connect.Client[v1.SubmitTranscriptionRequest, v1.Void]
	getYears              *connect.Client[v1.GetYearsRequest, v1.GetYearsResponse]
	getAlbums             *connect.Client[v1.GetAlbumsRequest, v1.AlbumsList]
	getAlbumTracks        *connect.Client[v1.GetAlbumTracksRequest, v1.TracksList]
	getPodcastTracks      *connect.Client[v1.GetPodcastTracksRequest, v1.TracksList]
	getLanguages          *connect.Client[v1.GetAvailableLanguagesRequest, v1.LanguageList]
	getBMMTranscription   *connect.Client[v1.GetBMMTranscriptionRequest, v1.Transcription]
	submitShort           *connect.Client[v1.SubmitShortRequest, v1.Void]
	getExportConfig       *connect.Client[v1.GetExportConfigRequest, v1.GetExportConfigResponse]
	startExport           *connect.Client[v1.StartExportRequest, v1.StartExportResponse]
	exportTimedMetadata   *connect.Client[v1.ExportTimedMetadataRequest, v1.Void]
	resolveAssets         *connect.Client[v1.ResolveAssetsRequest, v1.ResolveAssetsResponse]
	getVBExportConfig     *connect.Client[v1.GetVBExportConfigRequest, v1.GetVBExportConfigResponse]
	startVBExport         *connect.Client[v1.StartVBExportRequest, v1.StartVBExportResponse]
	getExportDestinations *connect.Client[v1.Void, v1.ExportDestinationsResponse]
	triggerCantemoAction  *connect.Client[v1.TriggerCantemoActionRequest, v1.Void]
	vaultSearch           *connect.Client[v1.VaultSearchRequest, v1.VaultSearchResponse]
	getVaultItem          *connect.Client[v1.GetVaultItemRequest, v1.GetVaultItemResponse]
}

// GetPermissions calls api.v1.APIService.GetPermissions.
func (c *aPIServiceClient) GetPermissions(ctx context.Context, req *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error) {
	return c.getPermissions.CallUnary(ctx, req)
}

// UpdatePermissions calls api.v1.APIService.UpdatePermissions.
func (c *aPIServiceClient) UpdatePermissions(ctx context.Context, req *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error) {
	return c.updatePermissions.CallUnary(ctx, req)
}

// DeletePermissions calls api.v1.APIService.DeletePermissions.
func (c *aPIServiceClient) DeletePermissions(ctx context.Context, req *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error) {
	return c.deletePermissions.CallUnary(ctx, req)
}

// ListPermissions calls api.v1.APIService.ListPermissions.
func (c *aPIServiceClient) ListPermissions(ctx context.Context, req *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error) {
	return c.listPermissions.CallUnary(ctx, req)
}

// GetTranscription calls api.v1.APIService.GetTranscription.
func (c *aPIServiceClient) GetTranscription(ctx context.Context, req *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error) {
	return c.getTranscription.CallUnary(ctx, req)
}

// GetPreview calls api.v1.APIService.GetPreview.
func (c *aPIServiceClient) GetPreview(ctx context.Context, req *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error) {
	return c.getPreview.CallUnary(ctx, req)
}

// SubmitTranscription calls api.v1.APIService.SubmitTranscription.
func (c *aPIServiceClient) SubmitTranscription(ctx context.Context, req *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error) {
	return c.submitTranscription.CallUnary(ctx, req)
}

// GetYears calls api.v1.APIService.GetYears.
func (c *aPIServiceClient) GetYears(ctx context.Context, req *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error) {
	return c.getYears.CallUnary(ctx, req)
}

// GetAlbums calls api.v1.APIService.GetAlbums.
func (c *aPIServiceClient) GetAlbums(ctx context.Context, req *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error) {
	return c.getAlbums.CallUnary(ctx, req)
}

// GetAlbumTracks calls api.v1.APIService.GetAlbumTracks.
func (c *aPIServiceClient) GetAlbumTracks(ctx context.Context, req *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return c.getAlbumTracks.CallUnary(ctx, req)
}

// GetPodcastTracks calls api.v1.APIService.GetPodcastTracks.
func (c *aPIServiceClient) GetPodcastTracks(ctx context.Context, req *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return c.getPodcastTracks.CallUnary(ctx, req)
}

// GetLanguages calls api.v1.APIService.GetLanguages.
func (c *aPIServiceClient) GetLanguages(ctx context.Context, req *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error) {
	return c.getLanguages.CallUnary(ctx, req)
}

// GetBMMTranscription calls api.v1.APIService.GetBMMTranscription.
func (c *aPIServiceClient) GetBMMTranscription(ctx context.Context, req *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error) {
	return c.getBMMTranscription.CallUnary(ctx, req)
}

// SubmitShort calls api.v1.APIService.SubmitShort.
func (c *aPIServiceClient) SubmitShort(ctx context.Context, req *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error) {
	return c.submitShort.CallUnary(ctx, req)
}

// GetExportConfig calls api.v1.APIService.GetExportConfig.
func (c *aPIServiceClient) GetExportConfig(ctx context.Context, req *connect.Request[v1.GetExportConfigRequest]) (*connect.Response[v1.GetExportConfigResponse], error) {
	return c.getExportConfig.CallUnary(ctx, req)
}

// StartExport calls api.v1.APIService.StartExport.
func (c *aPIServiceClient) StartExport(ctx context.Context, req *connect.Request[v1.StartExportRequest]) (*connect.Response[v1.StartExportResponse], error) {
	return c.startExport.CallUnary(ctx, req)
}

// ExportTimedMetadata calls api.v1.APIService.ExportTimedMetadata.
func (c *aPIServiceClient) ExportTimedMetadata(ctx context.Context, req *connect.Request[v1.ExportTimedMetadataRequest]) (*connect.Response[v1.Void], error) {
	return c.exportTimedMetadata.CallUnary(ctx, req)
}

// ResolveAssets calls api.v1.APIService.ResolveAssets.
func (c *aPIServiceClient) ResolveAssets(ctx context.Context, req *connect.Request[v1.ResolveAssetsRequest]) (*connect.Response[v1.ResolveAssetsResponse], error) {
	return c.resolveAssets.CallUnary(ctx, req)
}

// GetVBExportConfig calls api.v1.APIService.GetVBExportConfig.
func (c *aPIServiceClient) GetVBExportConfig(ctx context.Context, req *connect.Request[v1.GetVBExportConfigRequest]) (*connect.Response[v1.GetVBExportConfigResponse], error) {
	return c.getVBExportConfig.CallUnary(ctx, req)
}

// StartVBExport calls api.v1.APIService.StartVBExport.
func (c *aPIServiceClient) StartVBExport(ctx context.Context, req *connect.Request[v1.StartVBExportRequest]) (*connect.Response[v1.StartVBExportResponse], error) {
	return c.startVBExport.CallUnary(ctx, req)
}

// GetExportDestinations calls api.v1.APIService.GetExportDestinations.
func (c *aPIServiceClient) GetExportDestinations(ctx context.Context, req *connect.Request[v1.Void]) (*connect.Response[v1.ExportDestinationsResponse], error) {
	return c.getExportDestinations.CallUnary(ctx, req)
}

// TriggerCantemoAction calls api.v1.APIService.TriggerCantemoAction.
func (c *aPIServiceClient) TriggerCantemoAction(ctx context.Context, req *connect.Request[v1.TriggerCantemoActionRequest]) (*connect.Response[v1.Void], error) {
	return c.triggerCantemoAction.CallUnary(ctx, req)
}

// VaultSearch calls api.v1.APIService.VaultSearch.
func (c *aPIServiceClient) VaultSearch(ctx context.Context, req *connect.Request[v1.VaultSearchRequest]) (*connect.Response[v1.VaultSearchResponse], error) {
	return c.vaultSearch.CallUnary(ctx, req)
}

// GetVaultItem calls api.v1.APIService.GetVaultItem.
func (c *aPIServiceClient) GetVaultItem(ctx context.Context, req *connect.Request[v1.GetVaultItemRequest]) (*connect.Response[v1.GetVaultItemResponse], error) {
	return c.getVaultItem.CallUnary(ctx, req)
}

// APIServiceHandler is an implementation of the api.v1.APIService service.
type APIServiceHandler interface {
	// Permissions
	GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error)
	UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error)
	DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error)
	ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error)
	// Transcriptions
	GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error)
	GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error)
	SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error)
	// BMM
	GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error)
	GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error)
	GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error)
	GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error)
	// Shorts
	SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error)
	// Export
	GetExportConfig(context.Context, *connect.Request[v1.GetExportConfigRequest]) (*connect.Response[v1.GetExportConfigResponse], error)
	StartExport(context.Context, *connect.Request[v1.StartExportRequest]) (*connect.Response[v1.StartExportResponse], error)
	ExportTimedMetadata(context.Context, *connect.Request[v1.ExportTimedMetadataRequest]) (*connect.Response[v1.Void], error)
	// Resolve VX-ids to titles for the bulk-export asset list
	ResolveAssets(context.Context, *connect.Request[v1.ResolveAssetsRequest]) (*connect.Response[v1.ResolveAssetsResponse], error)
	// VB Export
	GetVBExportConfig(context.Context, *connect.Request[v1.GetVBExportConfigRequest]) (*connect.Response[v1.GetVBExportConfigResponse], error)
	StartVBExport(context.Context, *connect.Request[v1.StartVBExportRequest]) (*connect.Response[v1.StartVBExportResponse], error)
	// Full destination lists for the admin permission editor
	GetExportDestinations(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.ExportDestinationsResponse], error)
	// Cantemo action panel
	TriggerCantemoAction(context.Context, *connect.Request[v1.TriggerCantemoActionRequest]) (*connect.Response[v1.Void], error)
	// VAULT (Vidispine search)
	VaultSearch(context.Context, *connect.Request[v1.VaultSearchRequest]) (*connect.Response[v1.VaultSearchResponse], error)
	GetVaultItem(context.Context, *connect.Request[v1.GetVaultItemRequest]) (*connect.Response[v1.GetVaultItemResponse], error)
}

// NewAPIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAPIServiceHandler(svc APIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aPIServiceMethods := v1.File_api_v1_api_proto.Services().ByName("APIService").Methods()
	aPIServiceGetPermissionsHandler := connect.NewUnaryHandler(
		APIServiceGetPermissionsProcedure,
		svc.GetPermissions,
		connect.WithSchema(aPIServiceMethods.ByName("GetPermissions")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceUpdatePermissionsHandler := connect.NewUnaryHandler(
		APIServiceUpdatePermissionsProcedure,
		svc.UpdatePermissions,
		connect.WithSchema(aPIServiceMethods.ByName("UpdatePermissions")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceDeletePermissionsHandler := connect.NewUnaryHandler(
		APIServiceDeletePermissionsProcedure,
		svc.DeletePermissions,
		connect.WithSchema(aPIServiceMethods.ByName("DeletePermissions")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceListPermissionsHandler := connect.NewUnaryHandler(
		APIServiceListPermissionsProcedure,
		svc.ListPermissions,
		connect.WithSchema(aPIServiceMethods.ByName("ListPermissions")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceGetTranscriptionProcedure,
		svc.GetTranscription,
		connect.WithSchema(aPIServiceMethods.ByName("GetTranscription")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetPreviewHandler := connect.NewUnaryHandler(
		APIServiceGetPreviewProcedure,
		svc.GetPreview,
		connect.WithSchema(aPIServiceMethods.ByName("GetPreview")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceSubmitTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceSubmitTranscriptionProcedure,
		svc.SubmitTranscription,
		connect.WithSchema(aPIServiceMethods.ByName("SubmitTranscription")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetYearsHandler := connect.NewUnaryHandler(
		APIServiceGetYearsProcedure,
		svc.GetYears,
		connect.WithSchema(aPIServiceMethods.ByName("GetYears")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetAlbumsHandler := connect.NewUnaryHandler(
		APIServiceGetAlbumsProcedure,
		svc.GetAlbums,
		connect.WithSchema(aPIServiceMethods.ByName("GetAlbums")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetAlbumTracksHandler := connect.NewUnaryHandler(
		APIServiceGetAlbumTracksProcedure,
		svc.GetAlbumTracks,
		connect.WithSchema(aPIServiceMethods.ByName("GetAlbumTracks")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetPodcastTracksHandler := connect.NewUnaryHandler(
		APIServiceGetPodcastTracksProcedure,
		svc.GetPodcastTracks,
		connect.WithSchema(aPIServiceMethods.ByName("GetPodcastTracks")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetLanguagesHandler := connect.NewUnaryHandler(
		APIServiceGetLanguagesProcedure,
		svc.GetLanguages,
		connect.WithSchema(aPIServiceMethods.ByName("GetLanguages")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetBMMTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceGetBMMTranscriptionProcedure,
		svc.GetBMMTranscription,
		connect.WithSchema(aPIServiceMethods.ByName("GetBMMTranscription")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceSubmitShortHandler := connect.NewUnaryHandler(
		APIServiceSubmitShortProcedure,
		svc.SubmitShort,
		connect.WithSchema(aPIServiceMethods.ByName("SubmitShort")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetExportConfigHandler := connect.NewUnaryHandler(
		APIServiceGetExportConfigProcedure,
		svc.GetExportConfig,
		connect.WithSchema(aPIServiceMethods.ByName("GetExportConfig")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceStartExportHandler := connect.NewUnaryHandler(
		APIServiceStartExportProcedure,
		svc.StartExport,
		connect.WithSchema(aPIServiceMethods.ByName("StartExport")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceExportTimedMetadataHandler := connect.NewUnaryHandler(
		APIServiceExportTimedMetadataProcedure,
		svc.ExportTimedMetadata,
		connect.WithSchema(aPIServiceMethods.ByName("ExportTimedMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceResolveAssetsHandler := connect.NewUnaryHandler(
		APIServiceResolveAssetsProcedure,
		svc.ResolveAssets,
		connect.WithSchema(aPIServiceMethods.ByName("ResolveAssets")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetVBExportConfigHandler := connect.NewUnaryHandler(
		APIServiceGetVBExportConfigProcedure,
		svc.GetVBExportConfig,
		connect.WithSchema(aPIServiceMethods.ByName("GetVBExportConfig")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceStartVBExportHandler := connect.NewUnaryHandler(
		APIServiceStartVBExportProcedure,
		svc.StartVBExport,
		connect.WithSchema(aPIServiceMethods.ByName("StartVBExport")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetExportDestinationsHandler := connect.NewUnaryHandler(
		APIServiceGetExportDestinationsProcedure,
		svc.GetExportDestinations,
		connect.WithSchema(aPIServiceMethods.ByName("GetExportDestinations")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceTriggerCantemoActionHandler := connect.NewUnaryHandler(
		APIServiceTriggerCantemoActionProcedure,
		svc.TriggerCantemoAction,
		connect.WithSchema(aPIServiceMethods.ByName("TriggerCantemoAction")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceVaultSearchHandler := connect.NewUnaryHandler(
		APIServiceVaultSearchProcedure,
		svc.VaultSearch,
		connect.WithSchema(aPIServiceMethods.ByName("VaultSearch")),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetVaultItemHandler := connect.NewUnaryHandler(
		APIServiceGetVaultItemProcedure,
		svc.GetVaultItem,
		connect.WithSchema(aPIServiceMethods.ByName("GetVaultItem")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.APIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case APIServiceGetPermissionsProcedure:
			aPIServiceGetPermissionsHandler.ServeHTTP(w, r)
		case APIServiceUpdatePermissionsProcedure:
			aPIServiceUpdatePermissionsHandler.ServeHTTP(w, r)
		case APIServiceDeletePermissionsProcedure:
			aPIServiceDeletePermissionsHandler.ServeHTTP(w, r)
		case APIServiceListPermissionsProcedure:
			aPIServiceListPermissionsHandler.ServeHTTP(w, r)
		case APIServiceGetTranscriptionProcedure:
			aPIServiceGetTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceGetPreviewProcedure:
			aPIServiceGetPreviewHandler.ServeHTTP(w, r)
		case APIServiceSubmitTranscriptionProcedure:
			aPIServiceSubmitTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceGetYearsProcedure:
			aPIServiceGetYearsHandler.ServeHTTP(w, r)
		case APIServiceGetAlbumsProcedure:
			aPIServiceGetAlbumsHandler.ServeHTTP(w, r)
		case APIServiceGetAlbumTracksProcedure:
			aPIServiceGetAlbumTracksHandler.ServeHTTP(w, r)
		case APIServiceGetPodcastTracksProcedure:
			aPIServiceGetPodcastTracksHandler.ServeHTTP(w, r)
		case APIServiceGetLanguagesProcedure:
			aPIServiceGetLanguagesHandler.ServeHTTP(w, r)
		case APIServiceGetBMMTranscriptionProcedure:
			aPIServiceGetBMMTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceSubmitShortProcedure:
			aPIServiceSubmitShortHandler.ServeHTTP(w, r)
		case APIServiceGetExportConfigProcedure:
			aPIServiceGetExportConfigHandler.ServeHTTP(w, r)
		case APIServiceStartExportProcedure:
			aPIServiceStartExportHandler.ServeHTTP(w, r)
		case APIServiceExportTimedMetadataProcedure:
			aPIServiceExportTimedMetadataHandler.ServeHTTP(w, r)
		case APIServiceResolveAssetsProcedure:
			aPIServiceResolveAssetsHandler.ServeHTTP(w, r)
		case APIServiceGetVBExportConfigProcedure:
			aPIServiceGetVBExportConfigHandler.ServeHTTP(w, r)
		case APIServiceStartVBExportProcedure:
			aPIServiceStartVBExportHandler.ServeHTTP(w, r)
		case APIServiceGetExportDestinationsProcedure:
			aPIServiceGetExportDestinationsHandler.ServeHTTP(w, r)
		case APIServiceTriggerCantemoActionProcedure:
			aPIServiceTriggerCantemoActionHandler.ServeHTTP(w, r)
		case APIServiceVaultSearchProcedure:
			aPIServiceVaultSearchHandler.ServeHTTP(w, r)
		case APIServiceGetVaultItemProcedure:
			aPIServiceGetVaultItemHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAPIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAPIServiceHandler struct{}

func (UnimplementedAPIServiceHandler) GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.UpdatePermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.DeletePermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.ListPermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPreview is not implemented"))
}

func (UnimplementedAPIServiceHandler) SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.SubmitTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetYears is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetAlbums is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetAlbumTracks is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPodcastTracks is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetLanguages is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetBMMTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.SubmitShort is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetExportConfig(context.Context, *connect.Request[v1.GetExportConfigRequest]) (*connect.Response[v1.GetExportConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetExportConfig is not implemented"))
}

func (UnimplementedAPIServiceHandler) StartExport(context.Context, *connect.Request[v1.StartExportRequest]) (*connect.Response[v1.StartExportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.StartExport is not implemented"))
}

func (UnimplementedAPIServiceHandler) ExportTimedMetadata(context.Context, *connect.Request[v1.ExportTimedMetadataRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.ExportTimedMetadata is not implemented"))
}

func (UnimplementedAPIServiceHandler) ResolveAssets(context.Context, *connect.Request[v1.ResolveAssetsRequest]) (*connect.Response[v1.ResolveAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.ResolveAssets is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetVBExportConfig(context.Context, *connect.Request[v1.GetVBExportConfigRequest]) (*connect.Response[v1.GetVBExportConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetVBExportConfig is not implemented"))
}

func (UnimplementedAPIServiceHandler) StartVBExport(context.Context, *connect.Request[v1.StartVBExportRequest]) (*connect.Response[v1.StartVBExportResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.StartVBExport is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetExportDestinations(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.ExportDestinationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetExportDestinations is not implemented"))
}

func (UnimplementedAPIServiceHandler) TriggerCantemoAction(context.Context, *connect.Request[v1.TriggerCantemoActionRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.TriggerCantemoAction is not implemented"))
}

func (UnimplementedAPIServiceHandler) VaultSearch(context.Context, *connect.Request[v1.VaultSearchRequest]) (*connect.Response[v1.VaultSearchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.VaultSearch is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetVaultItem(context.Context, *connect.Request[v1.GetVaultItemRequest]) (*connect.Response[v1.GetVaultItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetVaultItem is not implemented"))
}
