// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/api.proto

package apiv1connect

import (
	v1 "bcc-media-tools/api/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// APIServiceName is the fully-qualified name of the APIService service.
	APIServiceName = "api.v1.APIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// APIServiceGetPermissionsProcedure is the fully-qualified name of the APIService's GetPermissions
	// RPC.
	APIServiceGetPermissionsProcedure = "/api.v1.APIService/GetPermissions"
	// APIServiceUpdatePermissionsProcedure is the fully-qualified name of the APIService's
	// UpdatePermissions RPC.
	APIServiceUpdatePermissionsProcedure = "/api.v1.APIService/UpdatePermissions"
	// APIServiceDeletePermissionsProcedure is the fully-qualified name of the APIService's
	// DeletePermissions RPC.
	APIServiceDeletePermissionsProcedure = "/api.v1.APIService/DeletePermissions"
	// APIServiceListPermissionsProcedure is the fully-qualified name of the APIService's
	// ListPermissions RPC.
	APIServiceListPermissionsProcedure = "/api.v1.APIService/ListPermissions"
	// APIServiceGetTranscriptionProcedure is the fully-qualified name of the APIService's
	// GetTranscription RPC.
	APIServiceGetTranscriptionProcedure = "/api.v1.APIService/GetTranscription"
	// APIServiceGetPreviewProcedure is the fully-qualified name of the APIService's GetPreview RPC.
	APIServiceGetPreviewProcedure = "/api.v1.APIService/GetPreview"
	// APIServiceSubmitTranscriptionProcedure is the fully-qualified name of the APIService's
	// SubmitTranscription RPC.
	APIServiceSubmitTranscriptionProcedure = "/api.v1.APIService/SubmitTranscription"
	// APIServiceGetYearsProcedure is the fully-qualified name of the APIService's GetYears RPC.
	APIServiceGetYearsProcedure = "/api.v1.APIService/GetYears"
	// APIServiceGetAlbumsProcedure is the fully-qualified name of the APIService's GetAlbums RPC.
	APIServiceGetAlbumsProcedure = "/api.v1.APIService/GetAlbums"
	// APIServiceGetAlbumTracksProcedure is the fully-qualified name of the APIService's GetAlbumTracks
	// RPC.
	APIServiceGetAlbumTracksProcedure = "/api.v1.APIService/GetAlbumTracks"
	// APIServiceGetPodcastTracksProcedure is the fully-qualified name of the APIService's
	// GetPodcastTracks RPC.
	APIServiceGetPodcastTracksProcedure = "/api.v1.APIService/GetPodcastTracks"
	// APIServiceGetLanguagesProcedure is the fully-qualified name of the APIService's GetLanguages RPC.
	APIServiceGetLanguagesProcedure = "/api.v1.APIService/GetLanguages"
	// APIServiceGetBMMTranscriptionProcedure is the fully-qualified name of the APIService's
	// GetBMMTranscription RPC.
	APIServiceGetBMMTranscriptionProcedure = "/api.v1.APIService/GetBMMTranscription"
	// APIServiceSubmitShortProcedure is the fully-qualified name of the APIService's SubmitShort RPC.
	APIServiceSubmitShortProcedure = "/api.v1.APIService/SubmitShort"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	aPIServiceServiceDescriptor                   = v1.File_api_v1_api_proto.Services().ByName("APIService")
	aPIServiceGetPermissionsMethodDescriptor      = aPIServiceServiceDescriptor.Methods().ByName("GetPermissions")
	aPIServiceUpdatePermissionsMethodDescriptor   = aPIServiceServiceDescriptor.Methods().ByName("UpdatePermissions")
	aPIServiceDeletePermissionsMethodDescriptor   = aPIServiceServiceDescriptor.Methods().ByName("DeletePermissions")
	aPIServiceListPermissionsMethodDescriptor     = aPIServiceServiceDescriptor.Methods().ByName("ListPermissions")
	aPIServiceGetTranscriptionMethodDescriptor    = aPIServiceServiceDescriptor.Methods().ByName("GetTranscription")
	aPIServiceGetPreviewMethodDescriptor          = aPIServiceServiceDescriptor.Methods().ByName("GetPreview")
	aPIServiceSubmitTranscriptionMethodDescriptor = aPIServiceServiceDescriptor.Methods().ByName("SubmitTranscription")
	aPIServiceGetYearsMethodDescriptor            = aPIServiceServiceDescriptor.Methods().ByName("GetYears")
	aPIServiceGetAlbumsMethodDescriptor           = aPIServiceServiceDescriptor.Methods().ByName("GetAlbums")
	aPIServiceGetAlbumTracksMethodDescriptor      = aPIServiceServiceDescriptor.Methods().ByName("GetAlbumTracks")
	aPIServiceGetPodcastTracksMethodDescriptor    = aPIServiceServiceDescriptor.Methods().ByName("GetPodcastTracks")
	aPIServiceGetLanguagesMethodDescriptor        = aPIServiceServiceDescriptor.Methods().ByName("GetLanguages")
	aPIServiceGetBMMTranscriptionMethodDescriptor = aPIServiceServiceDescriptor.Methods().ByName("GetBMMTranscription")
	aPIServiceSubmitShortMethodDescriptor         = aPIServiceServiceDescriptor.Methods().ByName("SubmitShort")
)

// APIServiceClient is a client for the api.v1.APIService service.
type APIServiceClient interface {
	// Permissions
	GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error)
	UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error)
	DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error)
	ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error)
	// Transcriptions
	GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error)
	GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error)
	SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error)
	// BMM
	GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error)
	GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error)
	GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error)
	GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error)
	// Shorts
	SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error)
}

// NewAPIServiceClient constructs a client for the api.v1.APIService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAPIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) APIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &aPIServiceClient{
		getPermissions: connect.NewClient[v1.Void, v1.Permissions](
			httpClient,
			baseURL+APIServiceGetPermissionsProcedure,
			connect.WithSchema(aPIServiceGetPermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updatePermissions: connect.NewClient[v1.SetPermissionsRequest, v1.Void](
			httpClient,
			baseURL+APIServiceUpdatePermissionsProcedure,
			connect.WithSchema(aPIServiceUpdatePermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deletePermissions: connect.NewClient[v1.DeletePermissionsRequest, v1.Void](
			httpClient,
			baseURL+APIServiceDeletePermissionsProcedure,
			connect.WithSchema(aPIServiceDeletePermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listPermissions: connect.NewClient[v1.Void, v1.PermissionsList](
			httpClient,
			baseURL+APIServiceListPermissionsProcedure,
			connect.WithSchema(aPIServiceListPermissionsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTranscription: connect.NewClient[v1.GetTranscriptionReqest, v1.Transcription](
			httpClient,
			baseURL+APIServiceGetTranscriptionProcedure,
			connect.WithSchema(aPIServiceGetTranscriptionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getPreview: connect.NewClient[v1.GetPreviewRequest, v1.Preview](
			httpClient,
			baseURL+APIServiceGetPreviewProcedure,
			connect.WithSchema(aPIServiceGetPreviewMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		submitTranscription: connect.NewClient[v1.SubmitTranscriptionRequest, v1.Void](
			httpClient,
			baseURL+APIServiceSubmitTranscriptionProcedure,
			connect.WithSchema(aPIServiceSubmitTranscriptionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getYears: connect.NewClient[v1.GetYearsRequest, v1.GetYearsResponse](
			httpClient,
			baseURL+APIServiceGetYearsProcedure,
			connect.WithSchema(aPIServiceGetYearsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAlbums: connect.NewClient[v1.GetAlbumsRequest, v1.AlbumsList](
			httpClient,
			baseURL+APIServiceGetAlbumsProcedure,
			connect.WithSchema(aPIServiceGetAlbumsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getAlbumTracks: connect.NewClient[v1.GetAlbumTracksRequest, v1.TracksList](
			httpClient,
			baseURL+APIServiceGetAlbumTracksProcedure,
			connect.WithSchema(aPIServiceGetAlbumTracksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getPodcastTracks: connect.NewClient[v1.GetPodcastTracksRequest, v1.TracksList](
			httpClient,
			baseURL+APIServiceGetPodcastTracksProcedure,
			connect.WithSchema(aPIServiceGetPodcastTracksMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getLanguages: connect.NewClient[v1.GetAvailableLanguagesRequest, v1.LanguageList](
			httpClient,
			baseURL+APIServiceGetLanguagesProcedure,
			connect.WithSchema(aPIServiceGetLanguagesMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getBMMTranscription: connect.NewClient[v1.GetBMMTranscriptionRequest, v1.Transcription](
			httpClient,
			baseURL+APIServiceGetBMMTranscriptionProcedure,
			connect.WithSchema(aPIServiceGetBMMTranscriptionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		submitShort: connect.NewClient[v1.SubmitShortRequest, v1.Void](
			httpClient,
			baseURL+APIServiceSubmitShortProcedure,
			connect.WithSchema(aPIServiceSubmitShortMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// aPIServiceClient implements APIServiceClient.
type aPIServiceClient struct {
	getPermissions      *connect.Client[v1.Void, v1.Permissions]
	updatePermissions   *connect.Client[v1.SetPermissionsRequest, v1.Void]
	deletePermissions   *connect.Client[v1.DeletePermissionsRequest, v1.Void]
	listPermissions     *connect.Client[v1.Void, v1.PermissionsList]
	getTranscription    *connect.Client[v1.GetTranscriptionReqest, v1.Transcription]
	getPreview          *connect.Client[v1.GetPreviewRequest, v1.Preview]
	submitTranscription *connect.Client[v1.SubmitTranscriptionRequest, v1.Void]
	getYears            *connect.Client[v1.GetYearsRequest, v1.GetYearsResponse]
	getAlbums           *connect.Client[v1.GetAlbumsRequest, v1.AlbumsList]
	getAlbumTracks      *connect.Client[v1.GetAlbumTracksRequest, v1.TracksList]
	getPodcastTracks    *connect.Client[v1.GetPodcastTracksRequest, v1.TracksList]
	getLanguages        *connect.Client[v1.GetAvailableLanguagesRequest, v1.LanguageList]
	getBMMTranscription *connect.Client[v1.GetBMMTranscriptionRequest, v1.Transcription]
	submitShort         *connect.Client[v1.SubmitShortRequest, v1.Void]
}

// GetPermissions calls api.v1.APIService.GetPermissions.
func (c *aPIServiceClient) GetPermissions(ctx context.Context, req *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error) {
	return c.getPermissions.CallUnary(ctx, req)
}

// UpdatePermissions calls api.v1.APIService.UpdatePermissions.
func (c *aPIServiceClient) UpdatePermissions(ctx context.Context, req *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error) {
	return c.updatePermissions.CallUnary(ctx, req)
}

// DeletePermissions calls api.v1.APIService.DeletePermissions.
func (c *aPIServiceClient) DeletePermissions(ctx context.Context, req *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error) {
	return c.deletePermissions.CallUnary(ctx, req)
}

// ListPermissions calls api.v1.APIService.ListPermissions.
func (c *aPIServiceClient) ListPermissions(ctx context.Context, req *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error) {
	return c.listPermissions.CallUnary(ctx, req)
}

// GetTranscription calls api.v1.APIService.GetTranscription.
func (c *aPIServiceClient) GetTranscription(ctx context.Context, req *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error) {
	return c.getTranscription.CallUnary(ctx, req)
}

// GetPreview calls api.v1.APIService.GetPreview.
func (c *aPIServiceClient) GetPreview(ctx context.Context, req *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error) {
	return c.getPreview.CallUnary(ctx, req)
}

// SubmitTranscription calls api.v1.APIService.SubmitTranscription.
func (c *aPIServiceClient) SubmitTranscription(ctx context.Context, req *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error) {
	return c.submitTranscription.CallUnary(ctx, req)
}

// GetYears calls api.v1.APIService.GetYears.
func (c *aPIServiceClient) GetYears(ctx context.Context, req *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error) {
	return c.getYears.CallUnary(ctx, req)
}

// GetAlbums calls api.v1.APIService.GetAlbums.
func (c *aPIServiceClient) GetAlbums(ctx context.Context, req *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error) {
	return c.getAlbums.CallUnary(ctx, req)
}

// GetAlbumTracks calls api.v1.APIService.GetAlbumTracks.
func (c *aPIServiceClient) GetAlbumTracks(ctx context.Context, req *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return c.getAlbumTracks.CallUnary(ctx, req)
}

// GetPodcastTracks calls api.v1.APIService.GetPodcastTracks.
func (c *aPIServiceClient) GetPodcastTracks(ctx context.Context, req *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return c.getPodcastTracks.CallUnary(ctx, req)
}

// GetLanguages calls api.v1.APIService.GetLanguages.
func (c *aPIServiceClient) GetLanguages(ctx context.Context, req *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error) {
	return c.getLanguages.CallUnary(ctx, req)
}

// GetBMMTranscription calls api.v1.APIService.GetBMMTranscription.
func (c *aPIServiceClient) GetBMMTranscription(ctx context.Context, req *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error) {
	return c.getBMMTranscription.CallUnary(ctx, req)
}

// SubmitShort calls api.v1.APIService.SubmitShort.
func (c *aPIServiceClient) SubmitShort(ctx context.Context, req *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error) {
	return c.submitShort.CallUnary(ctx, req)
}

// APIServiceHandler is an implementation of the api.v1.APIService service.
type APIServiceHandler interface {
	// Permissions
	GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error)
	UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error)
	DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error)
	ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error)
	// Transcriptions
	GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error)
	GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error)
	SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error)
	// BMM
	GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error)
	GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error)
	GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error)
	GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error)
	GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error)
	// Shorts
	SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error)
}

// NewAPIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAPIServiceHandler(svc APIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aPIServiceGetPermissionsHandler := connect.NewUnaryHandler(
		APIServiceGetPermissionsProcedure,
		svc.GetPermissions,
		connect.WithSchema(aPIServiceGetPermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceUpdatePermissionsHandler := connect.NewUnaryHandler(
		APIServiceUpdatePermissionsProcedure,
		svc.UpdatePermissions,
		connect.WithSchema(aPIServiceUpdatePermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceDeletePermissionsHandler := connect.NewUnaryHandler(
		APIServiceDeletePermissionsProcedure,
		svc.DeletePermissions,
		connect.WithSchema(aPIServiceDeletePermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceListPermissionsHandler := connect.NewUnaryHandler(
		APIServiceListPermissionsProcedure,
		svc.ListPermissions,
		connect.WithSchema(aPIServiceListPermissionsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceGetTranscriptionProcedure,
		svc.GetTranscription,
		connect.WithSchema(aPIServiceGetTranscriptionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetPreviewHandler := connect.NewUnaryHandler(
		APIServiceGetPreviewProcedure,
		svc.GetPreview,
		connect.WithSchema(aPIServiceGetPreviewMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceSubmitTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceSubmitTranscriptionProcedure,
		svc.SubmitTranscription,
		connect.WithSchema(aPIServiceSubmitTranscriptionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetYearsHandler := connect.NewUnaryHandler(
		APIServiceGetYearsProcedure,
		svc.GetYears,
		connect.WithSchema(aPIServiceGetYearsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetAlbumsHandler := connect.NewUnaryHandler(
		APIServiceGetAlbumsProcedure,
		svc.GetAlbums,
		connect.WithSchema(aPIServiceGetAlbumsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetAlbumTracksHandler := connect.NewUnaryHandler(
		APIServiceGetAlbumTracksProcedure,
		svc.GetAlbumTracks,
		connect.WithSchema(aPIServiceGetAlbumTracksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetPodcastTracksHandler := connect.NewUnaryHandler(
		APIServiceGetPodcastTracksProcedure,
		svc.GetPodcastTracks,
		connect.WithSchema(aPIServiceGetPodcastTracksMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetLanguagesHandler := connect.NewUnaryHandler(
		APIServiceGetLanguagesProcedure,
		svc.GetLanguages,
		connect.WithSchema(aPIServiceGetLanguagesMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceGetBMMTranscriptionHandler := connect.NewUnaryHandler(
		APIServiceGetBMMTranscriptionProcedure,
		svc.GetBMMTranscription,
		connect.WithSchema(aPIServiceGetBMMTranscriptionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aPIServiceSubmitShortHandler := connect.NewUnaryHandler(
		APIServiceSubmitShortProcedure,
		svc.SubmitShort,
		connect.WithSchema(aPIServiceSubmitShortMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.APIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case APIServiceGetPermissionsProcedure:
			aPIServiceGetPermissionsHandler.ServeHTTP(w, r)
		case APIServiceUpdatePermissionsProcedure:
			aPIServiceUpdatePermissionsHandler.ServeHTTP(w, r)
		case APIServiceDeletePermissionsProcedure:
			aPIServiceDeletePermissionsHandler.ServeHTTP(w, r)
		case APIServiceListPermissionsProcedure:
			aPIServiceListPermissionsHandler.ServeHTTP(w, r)
		case APIServiceGetTranscriptionProcedure:
			aPIServiceGetTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceGetPreviewProcedure:
			aPIServiceGetPreviewHandler.ServeHTTP(w, r)
		case APIServiceSubmitTranscriptionProcedure:
			aPIServiceSubmitTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceGetYearsProcedure:
			aPIServiceGetYearsHandler.ServeHTTP(w, r)
		case APIServiceGetAlbumsProcedure:
			aPIServiceGetAlbumsHandler.ServeHTTP(w, r)
		case APIServiceGetAlbumTracksProcedure:
			aPIServiceGetAlbumTracksHandler.ServeHTTP(w, r)
		case APIServiceGetPodcastTracksProcedure:
			aPIServiceGetPodcastTracksHandler.ServeHTTP(w, r)
		case APIServiceGetLanguagesProcedure:
			aPIServiceGetLanguagesHandler.ServeHTTP(w, r)
		case APIServiceGetBMMTranscriptionProcedure:
			aPIServiceGetBMMTranscriptionHandler.ServeHTTP(w, r)
		case APIServiceSubmitShortProcedure:
			aPIServiceSubmitShortHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAPIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAPIServiceHandler struct{}

func (UnimplementedAPIServiceHandler) GetPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.Permissions], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) UpdatePermissions(context.Context, *connect.Request[v1.SetPermissionsRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.UpdatePermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) DeletePermissions(context.Context, *connect.Request[v1.DeletePermissionsRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.DeletePermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) ListPermissions(context.Context, *connect.Request[v1.Void]) (*connect.Response[v1.PermissionsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.ListPermissions is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetTranscription(context.Context, *connect.Request[v1.GetTranscriptionReqest]) (*connect.Response[v1.Transcription], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetPreview(context.Context, *connect.Request[v1.GetPreviewRequest]) (*connect.Response[v1.Preview], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPreview is not implemented"))
}

func (UnimplementedAPIServiceHandler) SubmitTranscription(context.Context, *connect.Request[v1.SubmitTranscriptionRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.SubmitTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetYears(context.Context, *connect.Request[v1.GetYearsRequest]) (*connect.Response[v1.GetYearsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetYears is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetAlbums(context.Context, *connect.Request[v1.GetAlbumsRequest]) (*connect.Response[v1.AlbumsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetAlbums is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetAlbumTracks(context.Context, *connect.Request[v1.GetAlbumTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetAlbumTracks is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetPodcastTracks(context.Context, *connect.Request[v1.GetPodcastTracksRequest]) (*connect.Response[v1.TracksList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetPodcastTracks is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetLanguages(context.Context, *connect.Request[v1.GetAvailableLanguagesRequest]) (*connect.Response[v1.LanguageList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetLanguages is not implemented"))
}

func (UnimplementedAPIServiceHandler) GetBMMTranscription(context.Context, *connect.Request[v1.GetBMMTranscriptionRequest]) (*connect.Response[v1.Transcription], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.GetBMMTranscription is not implemented"))
}

func (UnimplementedAPIServiceHandler) SubmitShort(context.Context, *connect.Request[v1.SubmitShortRequest]) (*connect.Response[v1.Void], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.APIService.SubmitShort is not implemented"))
}
