export const LanguageMap = new Map()
	.set("nb", "Norwegian")
	.set("de", "German")
	.set("nl", "Dutch")
	.set("fr", "French")
	.set("ru", "Russian")
	.set("ro", "Romanian")
	.set("pl", "Polish")
	.set("bg", "Bulgarian")
	.set("hu", "Hungarian")
	.set("sl", "Slovenian")
	.set("hr", "Croatian")
	.set("tr", "Turkish")
	.set("en", "English")
	.set("es", "Spanish")
	.set("it", "Italian")
	.set("pt", "Portuguese")
	.set("fi", "Finnish")
	.set("zh", "Chinese")
	.set("da", "Danish")
	.set("yue", "Cantonese")
	.set("et", "Estonian")
	.set("kha", "Khasi")
	.set("af", "Afrikaans")
	.set("cs", "Czech")
	.set("ml", "Malayalam")
	.set("el", "Greek")
	.set("he", "Hebrew")
	.set("ta", "Tamil")
	.set("zxx", "Instrumental")

export function languageCodeToName(code: string) {
	if (!LanguageMap.has(code)) return code
	return LanguageMap.get(code)
}
