// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: api/v1/api.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BmmEnvironment int32

const (
	BmmEnvironment_Production  BmmEnvironment = 0
	BmmEnvironment_Integration BmmEnvironment = 1
)

// Enum value maps for BmmEnvironment.
var (
	BmmEnvironment_name = map[int32]string{
		0: "Production",
		1: "Integration",
	}
	BmmEnvironment_value = map[string]int32{
		"Production":  0,
		"Integration": 1,
	}
)

func (x BmmEnvironment) Enum() *BmmEnvironment {
	p := new(BmmEnvironment)
	*p = x
	return p
}

func (x BmmEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BmmEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_api_proto_enumTypes[0].Descriptor()
}

func (BmmEnvironment) Type() protoreflect.EnumType {
	return &file_api_v1_api_proto_enumTypes[0]
}

func (x BmmEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BmmEnvironment.Descriptor instead.
func (BmmEnvironment) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

type BMMPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []string               `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	Albums        []string               `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
	Podcasts      []string               `protobuf:"bytes,3,rep,name=podcasts,proto3" json:"podcasts,omitempty"`
	Admin         bool                   `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	Integration   bool                   `protobuf:"varint,5,opt,name=integration,proto3" json:"integration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMMPermission) Reset() {
	*x = BMMPermission{}
	mi := &file_api_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMMPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMMPermission) ProtoMessage() {}

func (x *BMMPermission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMMPermission.ProtoReflect.Descriptor instead.
func (*BMMPermission) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *BMMPermission) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *BMMPermission) GetAlbums() []string {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *BMMPermission) GetPodcasts() []string {
	if x != nil {
		return x.Podcasts
	}
	return nil
}

func (x *BMMPermission) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *BMMPermission) GetIntegration() bool {
	if x != nil {
		return x.Integration
	}
	return false
}

type TranscriptionPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         bool                   `protobuf:"varint,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Mediabanken   bool                   `protobuf:"varint,2,opt,name=mediabanken,proto3" json:"mediabanken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionPermission) Reset() {
	*x = TranscriptionPermission{}
	mi := &file_api_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionPermission) ProtoMessage() {}

func (x *TranscriptionPermission) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionPermission.ProtoReflect.Descriptor instead.
func (*TranscriptionPermission) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptionPermission) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *TranscriptionPermission) GetMediabanken() bool {
	if x != nil {
		return x.Mediabanken
	}
	return false
}

type Permissions struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Admin         bool                     `protobuf:"varint,1,opt,name=admin,proto3" json:"admin,omitempty"`
	Bmm           *BMMPermission           `protobuf:"bytes,2,opt,name=bmm,proto3" json:"bmm,omitempty"`
	Email         string                   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Transcription *TranscriptionPermission `protobuf:"bytes,4,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_api_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *Permissions) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *Permissions) GetBmm() *BMMPermission {
	if x != nil {
		return x.Bmm
	}
	return nil
}

func (x *Permissions) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Permissions) GetTranscription() *TranscriptionPermission {
	if x != nil {
		return x.Transcription
	}
	return nil
}

type GetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionsRequest) Reset() {
	*x = GetPermissionsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionsRequest) ProtoMessage() {}

func (x *GetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{3}
}

type SetPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Permissions   *Permissions           `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPermissionsRequest) Reset() {
	*x = SetPermissionsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermissionsRequest) ProtoMessage() {}

func (x *SetPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermissionsRequest.ProtoReflect.Descriptor instead.
func (*SetPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *SetPermissionsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetPermissionsRequest) GetPermissions() *Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type DeletePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionsRequest) Reset() {
	*x = DeletePermissionsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionsRequest) ProtoMessage() {}

func (x *DeletePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionsRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePermissionsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PermissionsList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Permissions   map[string]*Permissions `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionsList) Reset() {
	*x = PermissionsList{}
	mi := &file_api_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionsList) ProtoMessage() {}

func (x *PermissionsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionsList.ProtoReflect.Descriptor instead.
func (*PermissionsList) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *PermissionsList) GetPermissions() map[string]*Permissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type BMMYear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          uint32                 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BMMYear) Reset() {
	*x = BMMYear{}
	mi := &file_api_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMMYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMMYear) ProtoMessage() {}

func (x *BMMYear) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMMYear.ProtoReflect.Descriptor instead.
func (*BMMYear) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *BMMYear) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BMMYear) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetYearsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[uint32]*BMMYear    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetYearsResponse) Reset() {
	*x = GetYearsResponse{}
	mi := &file_api_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetYearsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetYearsResponse) ProtoMessage() {}

func (x *GetYearsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetYearsResponse.ProtoReflect.Descriptor instead.
func (*GetYearsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetYearsResponse) GetData() map[uint32]*BMMYear {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetYearsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   BmmEnvironment         `protobuf:"varint,1,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetYearsRequest) Reset() {
	*x = GetYearsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetYearsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetYearsRequest) ProtoMessage() {}

func (x *GetYearsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetYearsRequest.ProtoReflect.Descriptor instead.
func (*GetYearsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetYearsRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type GetAlbumsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          uint32                 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Environment   BmmEnvironment         `protobuf:"varint,2,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumsRequest) Reset() {
	*x = GetAlbumsRequest{}
	mi := &file_api_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumsRequest) ProtoMessage() {}

func (x *GetAlbumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumsRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetAlbumsRequest) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetAlbumsRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Languages     []string               `protobuf:"bytes,5,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_api_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Album) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type AlbumsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Albums        []*Album               `protobuf:"bytes,1,rep,name=albums,proto3" json:"albums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlbumsList) Reset() {
	*x = AlbumsList{}
	mi := &file_api_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlbumsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlbumsList) ProtoMessage() {}

func (x *AlbumsList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlbumsList.ProtoReflect.Descriptor instead.
func (*AlbumsList) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *AlbumsList) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

type GetAlbumTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlbumId       string                 `protobuf:"bytes,1,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	Environment   BmmEnvironment         `protobuf:"varint,2,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlbumTracksRequest) Reset() {
	*x = GetAlbumTracksRequest{}
	mi := &file_api_v1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlbumTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlbumTracksRequest) ProtoMessage() {}

func (x *GetAlbumTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlbumTracksRequest.ProtoReflect.Descriptor instead.
func (*GetAlbumTracksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetAlbumTracksRequest) GetAlbumId() string {
	if x != nil {
		return x.AlbumId
	}
	return ""
}

func (x *GetAlbumTracksRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type GetPodcastTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodcastTag    string                 `protobuf:"bytes,1,opt,name=podcast_tag,json=podcastTag,proto3" json:"podcast_tag,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Environment   BmmEnvironment         `protobuf:"varint,3,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodcastTracksRequest) Reset() {
	*x = GetPodcastTracksRequest{}
	mi := &file_api_v1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodcastTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodcastTracksRequest) ProtoMessage() {}

func (x *GetPodcastTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodcastTracksRequest.ProtoReflect.Descriptor instead.
func (*GetPodcastTracksRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetPodcastTracksRequest) GetPodcastTag() string {
	if x != nil {
		return x.PodcastTag
	}
	return ""
}

func (x *GetPodcastTracksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPodcastTracksRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type GetAvailableLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   BmmEnvironment         `protobuf:"varint,1,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableLanguagesRequest) Reset() {
	*x = GetAvailableLanguagesRequest{}
	mi := &file_api_v1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableLanguagesRequest) ProtoMessage() {}

func (x *GetAvailableLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableLanguagesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetAvailableLanguagesRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type BMMTrack struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	Languages         *LanguageList          `protobuf:"bytes,4,opt,name=languages,proto3" json:"languages,omitempty"`
	Transcriptions    *LanguageList          `protobuf:"bytes,5,opt,name=transcriptions,proto3" json:"transcriptions,omitempty"`
	HasTranscriptions bool                   `protobuf:"varint,6,opt,name=hasTranscriptions,proto3" json:"hasTranscriptions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BMMTrack) Reset() {
	*x = BMMTrack{}
	mi := &file_api_v1_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BMMTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BMMTrack) ProtoMessage() {}

func (x *BMMTrack) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BMMTrack.ProtoReflect.Descriptor instead.
func (*BMMTrack) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{16}
}

func (x *BMMTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BMMTrack) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BMMTrack) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *BMMTrack) GetLanguages() *LanguageList {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *BMMTrack) GetTranscriptions() *LanguageList {
	if x != nil {
		return x.Transcriptions
	}
	return nil
}

func (x *BMMTrack) GetHasTranscriptions() bool {
	if x != nil {
		return x.HasTranscriptions
	}
	return false
}

type TracksList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*BMMTrack            `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracksList) Reset() {
	*x = TracksList{}
	mi := &file_api_v1_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracksList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracksList) ProtoMessage() {}

func (x *TracksList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracksList.ProtoReflect.Descriptor instead.
func (*TracksList) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{17}
}

func (x *TracksList) GetTracks() []*BMMTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type LanguageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []*Language            `protobuf:"bytes,1,rep,name=Languages,proto3" json:"Languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageList) Reset() {
	*x = LanguageList{}
	mi := &file_api_v1_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageList) ProtoMessage() {}

func (x *LanguageList) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageList.ProtoReflect.Descriptor instead.
func (*LanguageList) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{18}
}

func (x *LanguageList) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

type Language struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	IconFile      string                 `protobuf:"bytes,3,opt,name=icon_file,json=iconFile,proto3" json:"icon_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_api_v1_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{19}
}

func (x *Language) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Language) GetIconFile() string {
	if x != nil {
		return x.IconFile
	}
	return ""
}

type GetTranscriptionReqest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VXID          string                 `protobuf:"bytes,1,opt,name=VXID,proto3" json:"VXID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptionReqest) Reset() {
	*x = GetTranscriptionReqest{}
	mi := &file_api_v1_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptionReqest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptionReqest) ProtoMessage() {}

func (x *GetTranscriptionReqest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptionReqest.ProtoReflect.Descriptor instead.
func (*GetTranscriptionReqest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{20}
}

func (x *GetTranscriptionReqest) GetVXID() string {
	if x != nil {
		return x.VXID
	}
	return ""
}

type Transcription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Segments      []*Segments            `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transcription) Reset() {
	*x = Transcription{}
	mi := &file_api_v1_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transcription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transcription) ProtoMessage() {}

func (x *Transcription) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transcription.ProtoReflect.Descriptor instead.
func (*Transcription) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{21}
}

func (x *Transcription) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Transcription) GetSegments() []*Segments {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Segments struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               float64                `protobuf:"fixed64,1,opt,name=id,proto3" json:"id,omitempty"`
	Seek             int32                  `protobuf:"varint,2,opt,name=seek,proto3" json:"seek,omitempty"`
	Start            float64                `protobuf:"fixed64,3,opt,name=start,proto3" json:"start,omitempty"`
	End              float64                `protobuf:"fixed64,4,opt,name=end,proto3" json:"end,omitempty"`
	Text             string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Tokens           []int32                `protobuf:"varint,6,rep,packed,name=tokens,proto3" json:"tokens,omitempty"`
	Temperature      float64                `protobuf:"fixed64,7,opt,name=temperature,proto3" json:"temperature,omitempty"`
	AvgLogprob       float64                `protobuf:"fixed64,8,opt,name=avg_logprob,json=avgLogprob,proto3" json:"avg_logprob,omitempty"`
	CompressionRatio float64                `protobuf:"fixed64,9,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	NoSpeechProb     float64                `protobuf:"fixed64,10,opt,name=no_speech_prob,json=noSpeechProb,proto3" json:"no_speech_prob,omitempty"`
	Confidence       float64                `protobuf:"fixed64,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Words            []*Words               `protobuf:"bytes,12,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Segments) Reset() {
	*x = Segments{}
	mi := &file_api_v1_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segments) ProtoMessage() {}

func (x *Segments) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segments.ProtoReflect.Descriptor instead.
func (*Segments) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{22}
}

func (x *Segments) GetId() float64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Segments) GetSeek() int32 {
	if x != nil {
		return x.Seek
	}
	return 0
}

func (x *Segments) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segments) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Segments) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Segments) GetTokens() []int32 {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *Segments) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Segments) GetAvgLogprob() float64 {
	if x != nil {
		return x.AvgLogprob
	}
	return 0
}

func (x *Segments) GetCompressionRatio() float64 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *Segments) GetNoSpeechProb() float64 {
	if x != nil {
		return x.NoSpeechProb
	}
	return 0
}

func (x *Segments) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Segments) GetWords() []*Words {
	if x != nil {
		return x.Words
	}
	return nil
}

type Words struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Start         float64                `protobuf:"fixed64,2,opt,name=start,proto3" json:"start,omitempty"`
	End           float64                `protobuf:"fixed64,3,opt,name=end,proto3" json:"end,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Words) Reset() {
	*x = Words{}
	mi := &file_api_v1_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Words) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Words) ProtoMessage() {}

func (x *Words) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Words.ProtoReflect.Descriptor instead.
func (*Words) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{23}
}

func (x *Words) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Words) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Words) GetEnd() float64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Words) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type GetPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VXID          string                 `protobuf:"bytes,1,opt,name=VXID,proto3" json:"VXID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreviewRequest) Reset() {
	*x = GetPreviewRequest{}
	mi := &file_api_v1_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreviewRequest) ProtoMessage() {}

func (x *GetPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreviewRequest.ProtoReflect.Descriptor instead.
func (*GetPreviewRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{24}
}

func (x *GetPreviewRequest) GetVXID() string {
	if x != nil {
		return x.VXID
	}
	return ""
}

type Preview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preview) Reset() {
	*x = Preview{}
	mi := &file_api_v1_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preview) ProtoMessage() {}

func (x *Preview) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preview.ProtoReflect.Descriptor instead.
func (*Preview) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{25}
}

func (x *Preview) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetBMMTranscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BmmId         string                 `protobuf:"bytes,1,opt,name=bmm_id,json=bmmId,proto3" json:"bmm_id,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Environment   BmmEnvironment         `protobuf:"varint,3,opt,name=environment,proto3,enum=api.v1.BmmEnvironment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBMMTranscriptionRequest) Reset() {
	*x = GetBMMTranscriptionRequest{}
	mi := &file_api_v1_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBMMTranscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBMMTranscriptionRequest) ProtoMessage() {}

func (x *GetBMMTranscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBMMTranscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetBMMTranscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{26}
}

func (x *GetBMMTranscriptionRequest) GetBmmId() string {
	if x != nil {
		return x.BmmId
	}
	return ""
}

func (x *GetBMMTranscriptionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetBMMTranscriptionRequest) GetEnvironment() BmmEnvironment {
	if x != nil {
		return x.Environment
	}
	return BmmEnvironment_Production
}

type SubmitTranscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VXID          string                 `protobuf:"bytes,1,opt,name=VXID,proto3" json:"VXID,omitempty"`
	Transcription *Transcription         `protobuf:"bytes,2,opt,name=transcription,proto3" json:"transcription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTranscriptionRequest) Reset() {
	*x = SubmitTranscriptionRequest{}
	mi := &file_api_v1_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTranscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTranscriptionRequest) ProtoMessage() {}

func (x *SubmitTranscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTranscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTranscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{27}
}

func (x *SubmitTranscriptionRequest) GetVXID() string {
	if x != nil {
		return x.VXID
	}
	return ""
}

func (x *SubmitTranscriptionRequest) GetTranscription() *Transcription {
	if x != nil {
		return x.Transcription
	}
	return nil
}

type SubmitShortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VXID          string                 `protobuf:"bytes,1,opt,name=VXID,proto3" json:"VXID,omitempty"`
	InSeconds     float64                `protobuf:"fixed64,2,opt,name=InSeconds,proto3" json:"InSeconds,omitempty"`
	OutSeconds    float64                `protobuf:"fixed64,3,opt,name=OutSeconds,proto3" json:"OutSeconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitShortRequest) Reset() {
	*x = SubmitShortRequest{}
	mi := &file_api_v1_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitShortRequest) ProtoMessage() {}

func (x *SubmitShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitShortRequest.ProtoReflect.Descriptor instead.
func (*SubmitShortRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_api_proto_rawDescGZIP(), []int{28}
}

func (x *SubmitShortRequest) GetVXID() string {
	if x != nil {
		return x.VXID
	}
	return ""
}

func (x *SubmitShortRequest) GetInSeconds() float64 {
	if x != nil {
		return x.InSeconds
	}
	return 0
}

func (x *SubmitShortRequest) GetOutSeconds() float64 {
	if x != nil {
		return x.OutSeconds
	}
	return 0
}

var File_api_v1_api_proto protoreflect.FileDescriptor

const file_api_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x10api/v1/api.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13api/v1/common.proto\"\x99\x01\n" +
	"\rBMMPermission\x12\x1c\n" +
	"\tlanguages\x18\x01 \x03(\tR\tlanguages\x12\x16\n" +
	"\x06albums\x18\x02 \x03(\tR\x06albums\x12\x1a\n" +
	"\bpodcasts\x18\x03 \x03(\tR\bpodcasts\x12\x14\n" +
	"\x05admin\x18\x04 \x01(\bR\x05admin\x12 \n" +
	"\vintegration\x18\x05 \x01(\bR\vintegration\"Q\n" +
	"\x17TranscriptionPermission\x12\x14\n" +
	"\x05admin\x18\x01 \x01(\bR\x05admin\x12 \n" +
	"\vmediabanken\x18\x02 \x01(\bR\vmediabanken\"\xa9\x01\n" +
	"\vPermissions\x12\x14\n" +
	"\x05admin\x18\x01 \x01(\bR\x05admin\x12'\n" +
	"\x03bmm\x18\x02 \x01(\v2\x15.api.v1.BMMPermissionR\x03bmm\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12E\n" +
	"\rtranscription\x18\x04 \x01(\v2\x1f.api.v1.TranscriptionPermissionR\rtranscription\"\x17\n" +
	"\x15GetPermissionsRequest\"d\n" +
	"\x15SetPermissionsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x125\n" +
	"\vpermissions\x18\x02 \x01(\v2\x13.api.v1.PermissionsR\vpermissions\"0\n" +
	"\x18DeletePermissionsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xb2\x01\n" +
	"\x0fPermissionsList\x12J\n" +
	"\vpermissions\x18\x01 \x03(\v2(.api.v1.PermissionsList.PermissionsEntryR\vpermissions\x1aS\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.api.v1.PermissionsR\x05value:\x028\x01\"3\n" +
	"\aBMMYear\x12\x12\n" +
	"\x04year\x18\x01 \x01(\rR\x04year\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x94\x01\n" +
	"\x10GetYearsResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".api.v1.GetYearsResponse.DataEntryR\x04data\x1aH\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.api.v1.BMMYearR\x05value:\x028\x01\"K\n" +
	"\x0fGetYearsRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"`\n" +
	"\x10GetAlbumsRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\rR\x04year\x128\n" +
	"\venvironment\x18\x02 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"a\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x04 \x01(\tR\x05cover\x12\x1c\n" +
	"\tlanguages\x18\x05 \x03(\tR\tlanguages\"3\n" +
	"\n" +
	"AlbumsList\x12%\n" +
	"\x06albums\x18\x01 \x03(\v2\r.api.v1.AlbumR\x06albums\"l\n" +
	"\x15GetAlbumTracksRequest\x12\x19\n" +
	"\balbum_id\x18\x01 \x01(\tR\aalbumId\x128\n" +
	"\venvironment\x18\x02 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"\x8a\x01\n" +
	"\x17GetPodcastTracksRequest\x12\x1f\n" +
	"\vpodcast_tag\x18\x01 \x01(\tR\n" +
	"podcastTag\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x128\n" +
	"\venvironment\x18\x03 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"X\n" +
	"\x1cGetAvailableLanguagesRequest\x128\n" +
	"\venvironment\x18\x01 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"\x8e\x02\n" +
	"\bBMMTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12<\n" +
	"\vpublishedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x122\n" +
	"\tlanguages\x18\x04 \x01(\v2\x14.api.v1.LanguageListR\tlanguages\x12<\n" +
	"\x0etranscriptions\x18\x05 \x01(\v2\x14.api.v1.LanguageListR\x0etranscriptions\x12,\n" +
	"\x11hasTranscriptions\x18\x06 \x01(\bR\x11hasTranscriptions\"6\n" +
	"\n" +
	"TracksList\x12(\n" +
	"\x06tracks\x18\x01 \x03(\v2\x10.api.v1.BMMTrackR\x06tracks\">\n" +
	"\fLanguageList\x12.\n" +
	"\tLanguages\x18\x01 \x03(\v2\x10.api.v1.LanguageR\tLanguages\";\n" +
	"\bLanguage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\ticon_file\x18\x03 \x01(\tR\biconFile\",\n" +
	"\x16GetTranscriptionReqest\x12\x12\n" +
	"\x04VXID\x18\x01 \x01(\tR\x04VXID\"Q\n" +
	"\rTranscription\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12,\n" +
	"\bsegments\x18\x02 \x03(\v2\x10.api.v1.SegmentsR\bsegments\"\xdd\x02\n" +
	"\bSegments\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x01R\x02id\x12\x12\n" +
	"\x04seek\x18\x02 \x01(\x05R\x04seek\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x01R\x03end\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x16\n" +
	"\x06tokens\x18\x06 \x03(\x05R\x06tokens\x12 \n" +
	"\vtemperature\x18\a \x01(\x01R\vtemperature\x12\x1f\n" +
	"\vavg_logprob\x18\b \x01(\x01R\n" +
	"avgLogprob\x12+\n" +
	"\x11compression_ratio\x18\t \x01(\x01R\x10compressionRatio\x12$\n" +
	"\x0eno_speech_prob\x18\n" +
	" \x01(\x01R\fnoSpeechProb\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\x05words\x18\f \x03(\v2\r.api.v1.WordsR\x05words\"c\n" +
	"\x05Words\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x01R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x01R\x03end\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"'\n" +
	"\x11GetPreviewRequest\x12\x12\n" +
	"\x04VXID\x18\x01 \x01(\tR\x04VXID\"\x1b\n" +
	"\aPreview\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x89\x01\n" +
	"\x1aGetBMMTranscriptionRequest\x12\x15\n" +
	"\x06bmm_id\x18\x01 \x01(\tR\x05bmmId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x128\n" +
	"\venvironment\x18\x03 \x01(\x0e2\x16.api.v1.BmmEnvironmentR\venvironment\"m\n" +
	"\x1aSubmitTranscriptionRequest\x12\x12\n" +
	"\x04VXID\x18\x01 \x01(\tR\x04VXID\x12;\n" +
	"\rtranscription\x18\x02 \x01(\v2\x15.api.v1.TranscriptionR\rtranscription\"f\n" +
	"\x12SubmitShortRequest\x12\x12\n" +
	"\x04VXID\x18\x01 \x01(\tR\x04VXID\x12\x1c\n" +
	"\tInSeconds\x18\x02 \x01(\x01R\tInSeconds\x12\x1e\n" +
	"\n" +
	"OutSeconds\x18\x03 \x01(\x01R\n" +
	"OutSeconds*1\n" +
	"\x0eBmmEnvironment\x12\x0e\n" +
	"\n" +
	"Production\x10\x00\x12\x0f\n" +
	"\vIntegration\x10\x012\xcb\a\n" +
	"\n" +
	"APIService\x125\n" +
	"\x0eGetPermissions\x12\f.api.v1.Void\x1a\x13.api.v1.Permissions\"\x00\x12B\n" +
	"\x11UpdatePermissions\x12\x1d.api.v1.SetPermissionsRequest\x1a\f.api.v1.Void\"\x00\x12E\n" +
	"\x11DeletePermissions\x12 .api.v1.DeletePermissionsRequest\x1a\f.api.v1.Void\"\x00\x12:\n" +
	"\x0fListPermissions\x12\f.api.v1.Void\x1a\x17.api.v1.PermissionsList\"\x00\x12K\n" +
	"\x10GetTranscription\x12\x1e.api.v1.GetTranscriptionReqest\x1a\x15.api.v1.Transcription\"\x00\x12:\n" +
	"\n" +
	"GetPreview\x12\x19.api.v1.GetPreviewRequest\x1a\x0f.api.v1.Preview\"\x00\x12I\n" +
	"\x13SubmitTranscription\x12\".api.v1.SubmitTranscriptionRequest\x1a\f.api.v1.Void\"\x00\x12?\n" +
	"\bGetYears\x12\x17.api.v1.GetYearsRequest\x1a\x18.api.v1.GetYearsResponse\"\x00\x12;\n" +
	"\tGetAlbums\x12\x18.api.v1.GetAlbumsRequest\x1a\x12.api.v1.AlbumsList\"\x00\x12E\n" +
	"\x0eGetAlbumTracks\x12\x1d.api.v1.GetAlbumTracksRequest\x1a\x12.api.v1.TracksList\"\x00\x12I\n" +
	"\x10GetPodcastTracks\x12\x1f.api.v1.GetPodcastTracksRequest\x1a\x12.api.v1.TracksList\"\x00\x12L\n" +
	"\fGetLanguages\x12$.api.v1.GetAvailableLanguagesRequest\x1a\x14.api.v1.LanguageList\"\x00\x12R\n" +
	"\x13GetBMMTranscription\x12\".api.v1.GetBMMTranscriptionRequest\x1a\x15.api.v1.Transcription\"\x00\x129\n" +
	"\vSubmitShort\x12\x1a.api.v1.SubmitShortRequest\x1a\f.api.v1.Void\"\x00B\x1eZ\x1cbcc-media-tools/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_api_proto_rawDescOnce sync.Once
	file_api_v1_api_proto_rawDescData []byte
)

func file_api_v1_api_proto_rawDescGZIP() []byte {
	file_api_v1_api_proto_rawDescOnce.Do(func() {
		file_api_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)))
	})
	return file_api_v1_api_proto_rawDescData
}

var file_api_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_v1_api_proto_goTypes = []any{
	(BmmEnvironment)(0),                  // 0: api.v1.BmmEnvironment
	(*BMMPermission)(nil),                // 1: api.v1.BMMPermission
	(*TranscriptionPermission)(nil),      // 2: api.v1.TranscriptionPermission
	(*Permissions)(nil),                  // 3: api.v1.Permissions
	(*GetPermissionsRequest)(nil),        // 4: api.v1.GetPermissionsRequest
	(*SetPermissionsRequest)(nil),        // 5: api.v1.SetPermissionsRequest
	(*DeletePermissionsRequest)(nil),     // 6: api.v1.DeletePermissionsRequest
	(*PermissionsList)(nil),              // 7: api.v1.PermissionsList
	(*BMMYear)(nil),                      // 8: api.v1.BMMYear
	(*GetYearsResponse)(nil),             // 9: api.v1.GetYearsResponse
	(*GetYearsRequest)(nil),              // 10: api.v1.GetYearsRequest
	(*GetAlbumsRequest)(nil),             // 11: api.v1.GetAlbumsRequest
	(*Album)(nil),                        // 12: api.v1.Album
	(*AlbumsList)(nil),                   // 13: api.v1.AlbumsList
	(*GetAlbumTracksRequest)(nil),        // 14: api.v1.GetAlbumTracksRequest
	(*GetPodcastTracksRequest)(nil),      // 15: api.v1.GetPodcastTracksRequest
	(*GetAvailableLanguagesRequest)(nil), // 16: api.v1.GetAvailableLanguagesRequest
	(*BMMTrack)(nil),                     // 17: api.v1.BMMTrack
	(*TracksList)(nil),                   // 18: api.v1.TracksList
	(*LanguageList)(nil),                 // 19: api.v1.LanguageList
	(*Language)(nil),                     // 20: api.v1.Language
	(*GetTranscriptionReqest)(nil),       // 21: api.v1.GetTranscriptionReqest
	(*Transcription)(nil),                // 22: api.v1.Transcription
	(*Segments)(nil),                     // 23: api.v1.Segments
	(*Words)(nil),                        // 24: api.v1.Words
	(*GetPreviewRequest)(nil),            // 25: api.v1.GetPreviewRequest
	(*Preview)(nil),                      // 26: api.v1.Preview
	(*GetBMMTranscriptionRequest)(nil),   // 27: api.v1.GetBMMTranscriptionRequest
	(*SubmitTranscriptionRequest)(nil),   // 28: api.v1.SubmitTranscriptionRequest
	(*SubmitShortRequest)(nil),           // 29: api.v1.SubmitShortRequest
	nil,                                  // 30: api.v1.PermissionsList.PermissionsEntry
	nil,                                  // 31: api.v1.GetYearsResponse.DataEntry
	(*timestamppb.Timestamp)(nil),        // 32: google.protobuf.Timestamp
	(*Void)(nil),                         // 33: api.v1.Void
}
var file_api_v1_api_proto_depIdxs = []int32{
	1,  // 0: api.v1.Permissions.bmm:type_name -> api.v1.BMMPermission
	2,  // 1: api.v1.Permissions.transcription:type_name -> api.v1.TranscriptionPermission
	3,  // 2: api.v1.SetPermissionsRequest.permissions:type_name -> api.v1.Permissions
	30, // 3: api.v1.PermissionsList.permissions:type_name -> api.v1.PermissionsList.PermissionsEntry
	31, // 4: api.v1.GetYearsResponse.data:type_name -> api.v1.GetYearsResponse.DataEntry
	0,  // 5: api.v1.GetYearsRequest.environment:type_name -> api.v1.BmmEnvironment
	0,  // 6: api.v1.GetAlbumsRequest.environment:type_name -> api.v1.BmmEnvironment
	12, // 7: api.v1.AlbumsList.albums:type_name -> api.v1.Album
	0,  // 8: api.v1.GetAlbumTracksRequest.environment:type_name -> api.v1.BmmEnvironment
	0,  // 9: api.v1.GetPodcastTracksRequest.environment:type_name -> api.v1.BmmEnvironment
	0,  // 10: api.v1.GetAvailableLanguagesRequest.environment:type_name -> api.v1.BmmEnvironment
	32, // 11: api.v1.BMMTrack.publishedAt:type_name -> google.protobuf.Timestamp
	19, // 12: api.v1.BMMTrack.languages:type_name -> api.v1.LanguageList
	19, // 13: api.v1.BMMTrack.transcriptions:type_name -> api.v1.LanguageList
	17, // 14: api.v1.TracksList.tracks:type_name -> api.v1.BMMTrack
	20, // 15: api.v1.LanguageList.Languages:type_name -> api.v1.Language
	23, // 16: api.v1.Transcription.segments:type_name -> api.v1.Segments
	24, // 17: api.v1.Segments.words:type_name -> api.v1.Words
	0,  // 18: api.v1.GetBMMTranscriptionRequest.environment:type_name -> api.v1.BmmEnvironment
	22, // 19: api.v1.SubmitTranscriptionRequest.transcription:type_name -> api.v1.Transcription
	3,  // 20: api.v1.PermissionsList.PermissionsEntry.value:type_name -> api.v1.Permissions
	8,  // 21: api.v1.GetYearsResponse.DataEntry.value:type_name -> api.v1.BMMYear
	33, // 22: api.v1.APIService.GetPermissions:input_type -> api.v1.Void
	5,  // 23: api.v1.APIService.UpdatePermissions:input_type -> api.v1.SetPermissionsRequest
	6,  // 24: api.v1.APIService.DeletePermissions:input_type -> api.v1.DeletePermissionsRequest
	33, // 25: api.v1.APIService.ListPermissions:input_type -> api.v1.Void
	21, // 26: api.v1.APIService.GetTranscription:input_type -> api.v1.GetTranscriptionReqest
	25, // 27: api.v1.APIService.GetPreview:input_type -> api.v1.GetPreviewRequest
	28, // 28: api.v1.APIService.SubmitTranscription:input_type -> api.v1.SubmitTranscriptionRequest
	10, // 29: api.v1.APIService.GetYears:input_type -> api.v1.GetYearsRequest
	11, // 30: api.v1.APIService.GetAlbums:input_type -> api.v1.GetAlbumsRequest
	14, // 31: api.v1.APIService.GetAlbumTracks:input_type -> api.v1.GetAlbumTracksRequest
	15, // 32: api.v1.APIService.GetPodcastTracks:input_type -> api.v1.GetPodcastTracksRequest
	16, // 33: api.v1.APIService.GetLanguages:input_type -> api.v1.GetAvailableLanguagesRequest
	27, // 34: api.v1.APIService.GetBMMTranscription:input_type -> api.v1.GetBMMTranscriptionRequest
	29, // 35: api.v1.APIService.SubmitShort:input_type -> api.v1.SubmitShortRequest
	3,  // 36: api.v1.APIService.GetPermissions:output_type -> api.v1.Permissions
	33, // 37: api.v1.APIService.UpdatePermissions:output_type -> api.v1.Void
	33, // 38: api.v1.APIService.DeletePermissions:output_type -> api.v1.Void
	7,  // 39: api.v1.APIService.ListPermissions:output_type -> api.v1.PermissionsList
	22, // 40: api.v1.APIService.GetTranscription:output_type -> api.v1.Transcription
	26, // 41: api.v1.APIService.GetPreview:output_type -> api.v1.Preview
	33, // 42: api.v1.APIService.SubmitTranscription:output_type -> api.v1.Void
	9,  // 43: api.v1.APIService.GetYears:output_type -> api.v1.GetYearsResponse
	13, // 44: api.v1.APIService.GetAlbums:output_type -> api.v1.AlbumsList
	18, // 45: api.v1.APIService.GetAlbumTracks:output_type -> api.v1.TracksList
	18, // 46: api.v1.APIService.GetPodcastTracks:output_type -> api.v1.TracksList
	19, // 47: api.v1.APIService.GetLanguages:output_type -> api.v1.LanguageList
	22, // 48: api.v1.APIService.GetBMMTranscription:output_type -> api.v1.Transcription
	33, // 49: api.v1.APIService.SubmitShort:output_type -> api.v1.Void
	36, // [36:50] is the sub-list for method output_type
	22, // [22:36] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_v1_api_proto_init() }
func file_api_v1_api_proto_init() {
	if File_api_v1_api_proto != nil {
		return
	}
	file_api_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_api_proto_rawDesc), len(file_api_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_api_proto_goTypes,
		DependencyIndexes: file_api_v1_api_proto_depIdxs,
		EnumInfos:         file_api_v1_api_proto_enumTypes,
		MessageInfos:      file_api_v1_api_proto_msgTypes,
	}.Build()
	File_api_v1_api_proto = out.File
	file_api_v1_api_proto_goTypes = nil
	file_api_v1_api_proto_depIdxs = nil
}
